[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 2}

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[cursor]
style = { shape = "Block", blinking = "always" }

[mouse]
hide_when_typing = true
